<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-OMRO4GL7" ignored="0" name="Test2" tests="2" failures="1" timestamp="28 Sep 2018 18:11:34 GMT" time="84.395" errors="0">
  <testcase name="testA" time="0.035" classname="script.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestDemo.testA(TestDemo.java:18)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase name="testdemo2" time="0.0" classname="script.TestDemo2"/>
</testsuite> <!-- Test2 -->
